[general]
working_directory = "/home/viggo"

# When on windows
# [terminal.shell]
# program = "pwsh"

[window]
opacity = 0.9
blur = false
padding.x = 8
padding.y = 8

[window.dimensions]
columns = 120
lines = 30

[font]
size = 12.0

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[cursor.style]
shape = "Beam"

# Colors (One Dark)
[colors.primary]
background = '#282c34'
foreground = '#abb2bf'

# Normal colors
[colors.normal]
black   = '#1e2127'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#abb2bf'

# Bright colors
[colors.bright]
black   = '#5c6370'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#ffffff'
